using Gym_Manager_System.DataFolder;
using Gym_Manager_System.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Gym_Manager_System.Face_Recognition
{
    public class AccessControlService
    {
        private readonly DatabaseContext _context;
        public AccessControlService(DatabaseContext context)
        {
            _context = context;
        }

        public async Task<Member?> GetMemberByFaceIdAsync(Guid personId)
        {
            using (var connection = _context.CreateConnection())
            {
                connection.Open();
                var command = connection.CreateCommand();
                command.CommandText = "SELECT * FROM members WHERE face_id = @personId";
                var param = command.CreateParameter();
                param.ParameterName = "@personId";
                param.Value = personId.ToString();
                command.Parameters.Add(param);
                using (var reader = command.ExecuteReader())
                {
                    if (reader.Read())
                    {
                        return new Member
                        {
                            MemberId = reader["member_id"] != DBNull.Value ? Convert.ToInt32(reader["member_id"]) : 0,
                            FirstName = reader["first_name"]?.ToString() ?? "",
                            LastName = reader["last_name"]?.ToString() ?? "",
                            Email = reader["email"]?.ToString() ?? "",
                            PhoneNumber = reader["phone"]?.ToString() ?? "",
                            DateOfBirth = reader["date_of_birth"] != DBNull.Value ? Convert.ToDateTime(reader["date_of_birth"]) : default,
                            JoinDate = reader["join_date"] != DBNull.Value ? Convert.ToDateTime(reader["join_date"]) : default,
                            Status = reader["status"]?.ToString() ?? "",
                            Emergency_contact_name = reader["emergency_contact_name"]?.ToString() ?? "",
                            Emergency_contact_phone = reader["emergency_contact_phone"]?.ToString() ?? "",
                            Medical_notes = reader["medical_notes"]?.ToString() ?? "",
                            FaceId = reader["face_id"] != DBNull.Value && reader["face_id"] != null ? reader["face_id"].ToString() : null
                        };
                    }
                    else
                    {
                        return null;
                    }
                }
            }
        }
        public async Task<bool> IsActiveMember(int memberId)
        {
            using (var connection = _context.CreateConnection())
            {
                connection.Open();
                var command = connection.CreateCommand();
                command.CommandText = "SELECT Status FROM members WHERE MemberId = @memberId";
                var param = command.CreateParameter();
                param.ParameterName = "@memberId";
                param.Value = memberId;
                command.Parameters.Add(param);
                var status = command.ExecuteScalar()?.ToString();
                try
                {
                    return status == "Active";
                }
                catch
                {
                    return false;
                }
            }
        }
        public async Task LogAccessAsync(int memberId, bool granted)
        {
            using (var connection = _context.CreateConnection())
            {
                connection.Open();
                var command = connection.CreateCommand();
                command.CommandText = "INSERT INTO face_checkin_logs (member_id, access_granted) VALUES (@memberId, @granted)";
                var param1 = command.CreateParameter();
                param1.ParameterName = "@memberId";
                param1.Value = memberId;
                command.Parameters.Add(param1);

                // param2 used to be timestamp, but delete it since auto-generated by MySQL

                var param3 = command.CreateParameter();
                param3.ParameterName = "@granted";
                param3.Value = granted;
                command.Parameters.Add(param3);
                command.ExecuteNonQuery();
            }
        }
        public async Task<(bool Success, string Message, Member? Member)> ProcessCheckInAsync(Guid? personId)
        {
            // No face detected or no match from Azure
            if (personId == null)
                return (false, "Face not recognized. Please see staff.", null);

            // Find member in database using Azure Person ID
            var member = await GetMemberByFaceIdAsync(personId.Value);
            if (member == null)
                return (false, "Member not found. Please see staff.", null);

            // Check if membership is active
            bool isActive = await IsActiveMember(member.MemberId);
            if (!isActive)
            {
                await LogAccessAsync(member.MemberId, false);
                return (false, $"Membership expired. Please renew at the front desk.", member);
            }

            // All good - log and grant access
            await LogAccessAsync(member.MemberId, true);
            return (true, $"Welcome, {member.FirstName} {member.LastName}!", member);
        }
    }
}
